// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TileWindowTests.Gherkin.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MovingFocusOrSwitchingVirtualDesktopsFeature : object, Xunit.IClassFixture<MovingFocusOrSwitchingVirtualDesktopsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "focus.feature"
#line hidden
        
        public MovingFocusOrSwitchingVirtualDesktopsFeature(MovingFocusOrSwitchingVirtualDesktopsFeature.FixtureData fixtureData, TileWindowTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "gherkin/features", "Moving focus or switching virtual desktops", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="When start virtual desktop 0 should be ActiveDesktop")]
        [Xunit.TraitAttribute("FeatureTitle", "Moving focus or switching virtual desktops")]
        [Xunit.TraitAttribute("Description", "When start virtual desktop 0 should be ActiveDesktop")]
        public virtual void WhenStartVirtualDesktop0ShouldBeActiveDesktop()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When start virtual desktop 0 should be ActiveDesktop", null, tagsOfScenario, argumentsOfScenario);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
    testRunner.Given("a primary screen \'screen1\' position 0x0 with resolution 1920x1080.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 5
    testRunner.Then("ActiveDesktop should be index \'0\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="When switching ActiveDesktop")]
        [Xunit.TraitAttribute("FeatureTitle", "Moving focus or switching virtual desktops")]
        [Xunit.TraitAttribute("Description", "When switching ActiveDesktop")]
        public virtual void WhenSwitchingActiveDesktop()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When switching ActiveDesktop", null, tagsOfScenario, argumentsOfScenario);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
    testRunner.Given("a primary screen \'screen1\' position 0x0 with resolution 1920x1080.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
    testRunner.When("switching ActiveDesktop to index \'1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
    testRunner.Then("ActiveDesktop should be index \'1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Two windows and one screen. Moving focus between them")]
        [Xunit.TraitAttribute("FeatureTitle", "Moving focus or switching virtual desktops")]
        [Xunit.TraitAttribute("Description", "Two windows and one screen. Moving focus between them")]
        [Xunit.InlineDataAttribute("vertical", "win1", "down", "win1", "win2", "move focus from top window down.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win1", "up", "win1", "win1", "move focus from top window up.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win1", "left", "win1", "win1", "move focus from top window left.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win1", "right", "win1", "win1", "move focus from top window right", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win2", "down", "win2", "win2", "move focus from bottom window down.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win2", "up", "win2", "win1", "move focus from bottom window up.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win2", "left", "win2", "win2", "move focus from bottom window left.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win2", "right", "win2", "win2", "move focus from bottom window right", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win1", "down", "win1", "win1", "move focus from left window down.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win1", "up", "win1", "win1", "move focus from left window up.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win1", "left", "win1", "win1", "move focus from left window left.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win1", "right", "win1", "win2", "move focus from left window right", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win2", "down", "win2", "win2", "move focus from right window down.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win2", "up", "win2", "win2", "move focus from right window up.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win2", "left", "win2", "win1", "move focus from right window left.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win2", "right", "win2", "win2", "move focus from right window right", new string[0])]
        public virtual void TwoWindowsAndOneScreen_MovingFocusBetweenThem(string orientation, string focus, string direction, string expect1, string expect2, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("orientation", orientation);
            argumentsOfScenario.Add("focus", focus);
            argumentsOfScenario.Add("direction", direction);
            argumentsOfScenario.Add("expect1", expect1);
            argumentsOfScenario.Add("expect2", expect2);
            argumentsOfScenario.Add("comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two windows and one screen. Moving focus between them", null, tagsOfScenario, argumentsOfScenario);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 13
    testRunner.Given("a primary screen \'screen1\' position 0x0 with resolution 1920x1080.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 14
    testRunner.And(string.Format("screen \'screen1\' has orientation {0}.", orientation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
    testRunner.And("a window \'win1\' on screen \'screen1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
    testRunner.And("a window \'win2\' on screen \'screen1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
    testRunner.And(string.Format("window \'{0}\' is focus.", focus), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
    testRunner.Then(string.Format("window \'{0}\' has focus.", expect1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
    testRunner.When(string.Format("moving focus {0}.", direction), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
    testRunner.Then(string.Format("window \'{0}\' has focus.", expect2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Three windows and one screen. Moving focus between them")]
        [Xunit.TraitAttribute("FeatureTitle", "Moving focus or switching virtual desktops")]
        [Xunit.TraitAttribute("Description", "Three windows and one screen. Moving focus between them")]
        [Xunit.InlineDataAttribute("vertical", "win1", "down", "win2", "win3", "move focus from top window down.", new string[0])]
        [Xunit.InlineDataAttribute("vertical", "win3", "up", "win2", "win1", "move focus from bottom window up.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win1", "right", "win2", "win3", "move focus from left window left.", new string[0])]
        [Xunit.InlineDataAttribute("horizontal", "win3", "left", "win2", "win1", "move focus from right window right.", new string[0])]
        public virtual void ThreeWindowsAndOneScreen_MovingFocusBetweenThem(string orientation, string focus, string direction, string expect1, string expect2, string comment, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("orientation", orientation);
            argumentsOfScenario.Add("focus", focus);
            argumentsOfScenario.Add("direction", direction);
            argumentsOfScenario.Add("expect1", expect1);
            argumentsOfScenario.Add("expect2", expect2);
            argumentsOfScenario.Add("comment", comment);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Three windows and one screen. Moving focus between them", null, tagsOfScenario, argumentsOfScenario);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 45
    testRunner.Given("a primary screen \'screen1\' position 0x0 with resolution 1920x1080.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 46
    testRunner.And(string.Format("screen \'screen1\' has orientation {0}.", orientation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
    testRunner.And("a window \'win1\' on screen \'screen1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
    testRunner.And("a window \'win2\' on screen \'screen1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
    testRunner.And("a window \'win3\' on screen \'screen1\'.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
    testRunner.And(string.Format("window \'{0}\' is focus.", focus), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
    testRunner.Then(string.Format("window \'{0}\' has focus.", focus), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
    testRunner.When(string.Format("moving focus {0}.", direction), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 53
    testRunner.Then(string.Format("window \'{0}\' has focus.", expect1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
    testRunner.When(string.Format("moving focus {0}.", direction), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
    testRunner.Then(string.Format("window \'{0}\' has focus.", expect2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MovingFocusOrSwitchingVirtualDesktopsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MovingFocusOrSwitchingVirtualDesktopsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
